#!/usr/bin/env python3
"""
Telegraph Heartbeat Publisher
Publishes OpenClaw status reports (tasks, calendar, metrics) to Telegraph
and sends Telegram notification with link.
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
import subprocess
import sys

# Add workspace scripts to path
sys.path.insert(0, os.path.expanduser("~/.openclaw/workspace/scripts"))

from telegraph_publisher import TelegraphPublisher


def get_pending_tasks() -> str:
    """Fetch pending tasks from Google Tasks."""
    try:
        # Using gog CLI to fetch tasks
        result = subprocess.run(
            ['gog', 'tasks', 'list', 'MDE3Mjg4NDY4MTYwNjc5NDE0MDY6MDow', 
             '-a', 'rdreilly2010@gmail.com', '--json'],
            capture_output=True,
            text=True,
            timeout=10
        )
        
        if result.returncode == 0:
            data = json.loads(result.stdout)
            tasks = data.get('tasks', [])
            pending = [t for t in tasks if t.get('status') == 'needsAction']
            
            if not pending:
                return "### Tasks\nNo pending tasks ✅"
            
            task_lines = ["### Tasks\n"]
            for task in pending[:10]:  # Limit to 10 most recent
                title = task.get('title', 'Untitled')
                due = task.get('due', '')
                due_str = f" (due: {due})" if due else ""
                task_lines.append(f"- {title}{due_str}")
            
            return "\n".join(task_lines)
    
    except Exception as e:
        return f"### Tasks\n⚠️ Error fetching tasks: {str(e)}"


def get_calendar_events() -> str:
    """Fetch upcoming calendar events."""
    try:
        result = subprocess.run(
            ['gog', 'calendar', 'list', '-a', 'rdreilly2010@gmail.com', '--json'],
            capture_output=True,
            text=True,
            timeout=10
        )
        
        if result.returncode == 0:
            data = json.loads(result.stdout)
            events = data.get('items', [])
            
            # Filter to next 24 hours
            now = datetime.now()
            tomorrow = now + timedelta(hours=24)
            
            upcoming = []
            for event in events:
                try:
                    start_str = event.get('start', {}).get('dateTime', '')
                    if start_str:
                        start = datetime.fromisoformat(start_str.replace('Z', '+00:00'))
                        if now <= start <= tomorrow:
                            upcoming.append(event)
                except:
                    pass
            
            if not upcoming:
                return "### Calendar\nNo upcoming events in next 24h"
            
            lines = ["### Calendar (Next 24h)\n"]
            for event in upcoming[:5]:
                title = event.get('summary', 'Untitled')
                time_str = event.get('start', {}).get('dateTime', '')
                if time_str:
                    # Parse and format time
                    try:
                        dt = datetime.fromisoformat(time_str.replace('Z', '+00:00'))
                        time_str = dt.strftime("%H:%M")
                    except:
                        pass
                
                lines.append(f"- {time_str}: {title}")
            
            return "\n".join(lines)
    
    except Exception as e:
        return f"### Calendar\n⚠️ Error fetching calendar: {str(e)}"


def get_system_status() -> str:
    """Get basic system status."""
    try:
        result = subprocess.run(
            ['uptime'],
            capture_output=True,
            text=True,
            timeout=5
        )
        
        if result.returncode == 0:
            uptime = result.stdout.strip()
            return f"### System Status\n- Uptime: {uptime}"
    
    except Exception:
        pass
    
    return "### System Status\n- Status: Running"


def create_heartbeat_report() -> str:
    """Create comprehensive heartbeat report in Markdown."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S EDT")
    
    report = f"""# OpenClaw Heartbeat Report

**Generated:** {timestamp}

{get_system_status()}

{get_pending_tasks()}

{get_calendar_events()}

---

*Report generated by Telegraph Heartbeat Publisher*
"""
    
    return report


def send_telegram_notification(telegraph_url: str, title: str = "OpenClaw Heartbeat") -> bool:
    """Send Telegram notification with Telegraph link."""
    try:
        # Get Telegram bot token and chat ID from environment or config
        telegram_bot_token = os.environ.get('TELEGRAM_BOT_TOKEN')
        telegram_chat_id = os.environ.get('TELEGRAM_CHAT_ID')
        
        if not telegram_bot_token or not telegram_chat_id:
            print("⚠️  Telegram credentials not configured (TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID)")
            return False
        
        message = f"📄 {title}\n{telegraph_url}"
        
        # Send via Telegram API
        url = f"https://api.telegram.org/bot{telegram_bot_token}/sendMessage"
        data = {
            'chat_id': telegram_chat_id,
            'text': message,
            'parse_mode': 'HTML'
        }
        
        import requests
        response = requests.post(url, json=data, timeout=10)
        
        if response.status_code == 200:
            print(f"✅ Telegram notification sent")
            return True
        else:
            print(f"⚠️  Telegram send failed: {response.status_code}")
            return False
    
    except Exception as e:
        print(f"⚠️  Error sending Telegram: {str(e)}")
        return False


def main():
    """Main heartbeat publishing routine."""
    print("[Heartbeat] Creating OpenClaw status report...")
    
    # Create report
    report = create_heartbeat_report()
    
    # Publish to Telegraph
    try:
        pub = TelegraphPublisher()
        
        title = f"OpenClaw Heartbeat - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        result = pub.publish_markdown(title, report)
        
        if result['success']:
            print(f"✅ Published to Telegraph: {result['url']}")
            
            # Try to send Telegram notification
            send_telegram_notification(result['url'], title)
            
            return 0
        else:
            print(f"❌ Publishing failed: {result['error']}")
            return 1
    
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return 1


if __name__ == '__main__':
    sys.exit(main())
