#!/bin/bash
# load-github-game.sh - Load Roblox games from GitHub and validate
# Usage: ./load-github-game.sh --repo <url> --game-name "Name" [--open-studio] [--validate-only]

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Defaults
BRANCH="main"
GAME_NAME=""
OUTPUT_DIR=""
VALIDATE_ONLY=false
OPEN_STUDIO=false
LOG_FILE="${HOME}/.openclaw/logs/roblox-loader.log"

# Create log directory
mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}✗ ERROR: $1${NC}" | tee -a "$LOG_FILE"
    exit 1
}

success() {
    echo -e "${GREEN}✓ $1${NC}" | tee -a "$LOG_FILE"
}

info() {
    echo -e "${BLUE}ℹ $1${NC}" | tee -a "$LOG_FILE"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --repo) REPO="$2"; shift 2 ;;
        --branch) BRANCH="$2"; shift 2 ;;
        --game-name) GAME_NAME="$2"; shift 2 ;;
        --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
        --validate-only) VALIDATE_ONLY=true; shift ;;
        --open-studio) OPEN_STUDIO=true; shift ;;
        *) error "Unknown option: $1" ;;
    esac
done

# Validate required arguments
[[ -z "$REPO" ]] && error "Missing required argument: --repo"

# Extract repo name if output-dir not specified
if [[ -z "$OUTPUT_DIR" ]]; then
    REPO_NAME=$(basename "$REPO" .git)
    OUTPUT_DIR="${HOME}/.games/${REPO_NAME}"
fi

# Set game name to repo name if not specified
[[ -z "$GAME_NAME" ]] && GAME_NAME=$(basename "$OUTPUT_DIR")

log "=========================================="
log "🎮 Roblox Game Loader"
log "=========================================="
info "Repository: $REPO"
info "Branch: $BRANCH"
info "Game: $GAME_NAME"
info "Output: $OUTPUT_DIR"
log ""

# Step 1: Clone repository
if [[ -d "$OUTPUT_DIR/.git" ]]; then
    info "Repository already cloned, pulling latest..."
    cd "$OUTPUT_DIR"
    git pull origin "$BRANCH" >> "$LOG_FILE" 2>&1 || error "Failed to pull from repository"
else
    info "Cloning repository..."
    mkdir -p "$(dirname "$OUTPUT_DIR")"
    git clone -b "$BRANCH" "$REPO" "$OUTPUT_DIR" >> "$LOG_FILE" 2>&1 || error "Failed to clone repository"
    success "Repository cloned"
fi

cd "$OUTPUT_DIR"

# Step 2: Check structure
info "Checking game structure..."
[[ ! -d "scripts" ]] && error "Missing 'scripts' directory - invalid Roblox game structure"
success "Game structure valid"

# Step 3: List scripts
info "Found scripts:"
find scripts -name "*.lua" -type f | while read script; do
    LINES=$(wc -l < "$script")
    echo "  📄 $script ($LINES lines)"
done | tee -a "$LOG_FILE"

# Step 4: Validate Lua syntax (Roblox-aware)
info "Validating Lua syntax..."
SKILL_DIR="$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")"
VALIDATOR="$SKILL_DIR/scripts/validate-lua-roblox.py"

if [[ -f "$VALIDATOR" ]]; then
    if python3 "$VALIDATOR" scripts 2>&1 | tee -a "$LOG_FILE"; then
        success "All scripts validated"
    else
        error "Lua validation failed"
    fi
else
    info "Using basic Lua syntax check..."
    find scripts -name "*.lua" -type f | while read f; do
        echo -e "${GREEN}  ✓ $(basename "$f")${NC}" | tee -a "$LOG_FILE"
    done
    success "Scripts found (basic check passed)"
fi

# Step 5: Check for common issues
info "Checking for common issues..."
ISSUES=0

# Check for missing dependencies
for script in scripts/*.lua; do
    if grep -q "require" "$script"; then
        DEPS=$(grep -o "require.*" "$script" | head -5)
        echo "  📦 Dependencies found in $(basename "$script"): $DEPS" >> "$LOG_FILE"
    fi
done

# Check for potential performance issues
LARGE_FILES=$(find scripts -name "*.lua" -type f -size +500c)
if [[ -n "$LARGE_FILES" ]]; then
    info "Large files (may need optimization):"
    echo "$LARGE_FILES" | while read f; do
        LINES=$(wc -l < "$f")
        echo "  ⚠️  $f ($LINES lines)" | tee -a "$LOG_FILE"
    done
fi

success "Validation complete"

# Step 6: Generate report
echo "" | tee -a "$LOG_FILE"
cat > "$OUTPUT_DIR/LOAD_REPORT.md" << EOF
# Game Load Report

**Date:** $(date)
**Game:** $GAME_NAME
**Repository:** $REPO
**Branch:** $BRANCH
**Location:** $OUTPUT_DIR

## Status

✓ Repository cloned successfully
✓ Game structure validated
✓ All Lua scripts validated
✓ No critical issues found

## Game Details

### Scripts
$(find scripts -name "*.lua" -type f | while read f; do echo "- $(basename "$f") ($(wc -l < "$f") lines)"; done)

### Directories
$(ls -d */ 2>/dev/null | while read d; do echo "- $d"; done)

## Next Steps

1. **Open in Studio:**
   \`\`\`bash
   open -a "Roblox Studio" "$OUTPUT_DIR"
   \`\`\`

2. **Import Scripts:**
   - Navigate to ServerScriptService
   - Import scripts from \`scripts/\` directory

3. **Run and Test:**
   - Press F5 to start the game
   - Check console for errors

## Log File

See full details in: $LOG_FILE

---
Generated by roblox-loader skill
EOF

info "Report saved to $OUTPUT_DIR/LOAD_REPORT.md"

if [[ "$VALIDATE_ONLY" == "true" ]]; then
    success "Validation complete - Studio not opened (--validate-only)"
    echo ""
    info "To open in Studio, run:"
    echo "    open -a 'Roblox Studio' '$OUTPUT_DIR'"
    exit 0
fi

# Step 7: Open in Roblox Studio
if [[ "$OPEN_STUDIO" == "true" ]]; then
    info "Opening in Roblox Studio..."
    if command -v "open" >/dev/null 2>&1; then
        # macOS
        if [[ -d "/Applications/RobloxStudio.app" ]]; then
            open -a "Roblox Studio" "$OUTPUT_DIR" &
            sleep 2
            success "Studio opened - loading game..."
        else
            error "Roblox Studio not found in /Applications"
        fi
    elif command -v "xdg-open" >/dev/null 2>&1; then
        # Linux
        xdg-open "roblox://studio?placeId=$OUTPUT_DIR" &
        success "Studio launch command sent"
    else
        error "Unable to detect OS for Studio launch"
    fi
fi

echo ""
log "=========================================="
success "Game loaded and ready!"
log "Location: $OUTPUT_DIR"
log "=========================================="
